// Filepath: src/chat_interface.tsx

import {useState} from "react";

import {
    ChatHeader,
    MessageSendButton,
    MessageSendField,
    ChatWindow
} from "./chat_interface.componant.tsx";
import type {AIResponse} from './model.aiResponse.ts';

const demoAIResponse: AIResponse = {
    heading: "Deadlock in Operating Systems",
    introduction:
        "Deadlock is a situation where processes are permanently blocked while waiting for resources.",
    tags: ["OS", "Deadlock", "Concurrency"],

    definition: {
        term: "Deadlock",
        meaning: "A condition where no process can proceed execution.",
    },

    points: [
        "Occurs in multi-process environments",
        "Processes wait indefinitely",
        "System throughput becomes zero",
    ],

    steps: [
        "Process requests resource",
        "Resource is held",
        "Another resource is requested",
        "Circular wait forms",
    ],

    warning: "Deadlocks can freeze mission-critical systems.",

    code: `while(true) {
    wait();
}`,

    table: {
        headers: ["Condition", "Required"],
        rows: [
            ["Mutual Exclusion", "Yes"],
            ["Hold and Wait", "Yes"],
            ["No Preemption", "Yes"],
            ["Circular Wait", "Yes"],
        ],
    },

    summary:
        "Deadlock is a serious operating system issue that must be prevented or avoided.",
    footer: "Generated by AI · 2025",
};


export default function ChatInterface() {

    const [textFieldMessage, setTextFieldMessage] = useState<string>('');
    type Message =
        | { type: "user"; text: string }
        | { type: "ai-text"; text: string }
        | { type: "ai-structured"; data: typeof AIResponse };

    const [messages, setMessages] = useState<Message[]>([]);


    const showMessage = () => {
        if (!textFieldMessage) return;

        // Add user's message
        setMessages((prev) => [...prev, { text: textFieldMessage, isSent: true }]);
        setTextFieldMessage("");

        // Simulate a received reply after 1 second
        setTimeout(() => {
            setMessages((prev) => [
                ...prev,
                { text: "This is a simulated reply!", isSent: false },
            ]);
        }, 1000);
    };

    return (
        <div className={'w-screen h-screen bg-black text-white align-middle flex flex-col items-center justify-center py-3'}>

            <ChatHeader name={"MD. Adnan Abdullah Sadi"} subtext={"User"}/>

            <ChatWindow messages={messages} />


            <div className={'flex items-center justify-center gap-2 w-screen pb-6'}>
                <MessageSendField textFieldMessage={textFieldMessage} setTextFieldMessage={setTextFieldMessage}/>

                <MessageSendButton showMessage={showMessage}/>

            </div>



        </div>
    );


}

/*
---Compulsory---
Heading
introduction
tag
footer
summary

---Optional---
code section
image
YouTube video like
MediaWiki, website link
point
quote
definition
point
warning
tips
table
steps

 */
