// Filepath: src/chat_interface.tsx

import { useState } from "react";

import {
    ChatHeader,
    MessageSendButton,
    MessageSendField,
    ChatWindow,
} from "./chat_interface.componant";
import type { AIResponse, Message } from "./model.aiResponse";


const demoAIResponse: AIResponse = {
    heading: "Deadlock in Operating Systems",
    introduction:
        "Deadlock is a situation where processes are permanently blocked while waiting for resources.",
    tags: ["OS", "Deadlock", "Concurrency"],

    definition: {
        term: "Deadlock",
        meaning: "A condition where no process can proceed execution.",
    },

    points: {
        heading: 'Something',
        point: [
            "Occurs in multi-process environments",
            "Processes wait indefinitely",
            "System throughput becomes zero",
]
    },

    steps: {
        heading: 'Heading',
        point: [
            "Process requests resource",
            "Resource is held",
            "Another resource is requested",
            "Circular wait forms",
        ]

    },

    warning: {
        heading: "Warning",
        text:  "Deadlocks can freeze mission-critical systems.",
    },

    tips: {
        heading: "Tips",
        text:  "Deadlocks can freeze mission-critical systems.",
    },

    code: `while(true) {
  wait();
}`,

    table: {
        headers: ["Condition", "Required", "Condition", "Required"],
        rows: [
            ["Mutual Exclusion", "Yes", "Mutual Exclusion", "Yes"],
            ["Hold and Wait", "Yes", "Mutual Exclusion", "Yes"],
            ["No Preemption", "Yes", "Mutual Exclusion", "Yes"],
            ["Circular Wait", "Yes", "Mutual Exclusion", "Yes"],
        ],
    },

    summary:
        "Deadlock is a serious operating system issue that must be prevented or avoided.",
    footer: "Generated by AI · 2025",
};




// ---------------- COMPONENT ----------------
export default function ChatInterface() {

    const [textFieldMessage, setTextFieldMessage] = useState("");
    const [messages, setMessages] = useState<Message[]>([]);




    const showMessage = () => {
        if (!textFieldMessage.trim()) return;

        // user message
        setMessages((prev) => [
            ...prev,
            { type: "user", text: textFieldMessage },
        ]);

        setTextFieldMessage("");

        // simulated AI structured response
        setTimeout(() => {
            setMessages((prev) => [
                ...prev,
                { type: "ai-structured", data: demoAIResponse },
            ]);
        }, 1000);
    };


    return (
        <div className="w-screen h-screen bg-black text-white flex flex-col items-center justify-center py-3">
            <ChatHeader name={"MD. Adnan Abdullah Sadi"} subtext={"User"} />

            <ChatWindow messages={messages} />

            <div className="flex items-center justify-center gap-2 w-screen pb-6">
                <MessageSendField
                    textFieldMessage={textFieldMessage}
                    setTextFieldMessage={setTextFieldMessage}
                />

                <MessageSendButton showMessage={showMessage} />
            </div>
        </div>
    );
}
